@startmindmap
title Паттерны

* Паттерны

** Поведенческий
*** Цепочка обязанностей
*** Команда
*** Интерпретатор
*** Итератор
*** Посредник
*** Хранитель
*** Наблюдатель
*** Состояние
*** Стратегия
*** Шаблонный методо
*** Посетитель

** Структурный
*** Адаптер
*** Мост
*** Компоновщик
*** Декоратор
*** Фасад
*** Приспособленец
*** Прокси

** Порождающий
*** Абстрактная фабрика
*** Строитель
*** Фабричный метод
*** Прототип
*** Одиночка
@endmindmap
